version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: jxc_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: jxc_db
      MYSQL_USER: jxc_user
      MYSQL_PASSWORD: jxc_password
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init:/docker-entrypoint-initdb.d
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone='+08:00'
      --lower_case_table_names=1
    networks:
      - jxc_network

  redis:
    image: redis:7.2-alpine
    container_name: jxc_redis
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass 123456 --appendonly yes
    networks:
      - jxc_network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  jxc_network:
    driver: bridge