version: '3.8'

services:
  # 前端应用
  jxc-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:8080/api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - jxc-network

  # 后端API服务（示例配置，根据实际后端调整）
  jxc-backend:
    image: your-backend-image:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:mysql://db:3306/jxc
      - DATABASE_USERNAME=jxc_user
      - DATABASE_PASSWORD=your_password
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - jxc-network

  # 数据库服务（示例配置）
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=jxc
      - MYSQL_USER=jxc_user
      - MYSQL_PASSWORD=your_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - jxc-network

  # Redis缓存服务（可选）
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - jxc-network

volumes:
  mysql_data:
  redis_data:

networks:
  jxc-network:
    driver: bridge